// Mock data for Gantt timelines (TOGAF, PRINCE2, PMBOK)

import { GanttTask } from "./types/gantt"

// TOGAF ADM mock tasks
export const togafMockTasks: GanttTask[] = [
  // Preliminary Phase
  {
    id: "togaf-1",
    title: "Establish Architecture Capability",
    description: "Set up architecture team and tools",
    status: "preliminary",
    frameworkId: "togaf",
    assignee: { id: "user-1", name: "Architecture Lead", avatar: "AL" },
    priority: "high",
    tags: ["setup", "governance"],
    startDate: new Date(2025, 0, 1),
    endDate: new Date(2025, 0, 15),
    progress: 100,
    metadata: { type: "Work Package", phase: "Preliminary", isMilestone: false },
    createdAt: new Date("2025-01-01"),
    updatedAt: new Date("2025-01-15"),
  },
  {
    id: "togaf-2",
    title: "Define Architecture Principles",
    description: "Document guiding principles for EA",
    status: "preliminary",
    frameworkId: "togaf",
    assignee: { id: "user-1", name: "Architecture Lead", avatar: "AL" },
    priority: "high",
    tags: ["principles", "documentation"],
    startDate: new Date(2025, 0, 10),
    endDate: new Date(2025, 0, 25),
    progress: 100,
    dependencies: ["togaf-1"],
    metadata: { type: "Architecture Deliverable", phase: "Preliminary" },
    createdAt: new Date("2025-01-10"),
    updatedAt: new Date("2025-01-25"),
  },

  // Phase A: Architecture Vision
  {
    id: "togaf-3",
    title: "Stakeholder Analysis",
    description: "Identify and analyze key stakeholders",
    status: "phase-a",
    frameworkId: "togaf",
    assignee: { id: "user-2", name: "Business Analyst", avatar: "BA" },
    priority: "high",
    tags: ["stakeholders", "analysis"],
    startDate: new Date(2025, 0, 20),
    endDate: new Date(2025, 1, 5),
    progress: 85,
    dependencies: ["togaf-2"],
    metadata: { type: "Work Package", phase: "Phase A" },
    createdAt: new Date("2025-01-20"),
    updatedAt: new Date("2025-01-28"),
  },
  {
    id: "togaf-4",
    title: "Architecture Vision Document",
    description: "Create high-level architecture vision",
    status: "phase-a",
    frameworkId: "togaf",
    assignee: { id: "user-1", name: "Architecture Lead", avatar: "AL" },
    priority: "critical",
    tags: ["vision", "deliverable"],
    startDate: new Date(2025, 1, 1),
    endDate: new Date(2025, 1, 20),
    progress: 60,
    dependencies: ["togaf-3"],
    metadata: { type: "Architecture Deliverable", phase: "Phase A", isMilestone: true },
    createdAt: new Date("2025-02-01"),
    updatedAt: new Date("2025-02-15"),
  },

  // Phase B: Business Architecture
  {
    id: "togaf-5",
    title: "Business Capability Map",
    description: "Document current business capabilities",
    status: "phase-b",
    frameworkId: "togaf",
    assignee: { id: "user-2", name: "Business Analyst", avatar: "BA" },
    priority: "high",
    tags: ["capabilities", "baseline"],
    startDate: new Date(2025, 1, 15),
    endDate: new Date(2025, 2, 10),
    progress: 40,
    dependencies: ["togaf-4"],
    metadata: { type: "Building Block", phase: "Phase B" },
    createdAt: new Date("2025-02-15"),
    updatedAt: new Date("2025-02-20"),
  },
  {
    id: "togaf-6",
    title: "Business Process Models",
    description: "Model key business processes",
    status: "phase-b",
    frameworkId: "togaf",
    assignee: { id: "user-3", name: "Process Architect", avatar: "PA" },
    priority: "medium",
    tags: ["processes", "modeling"],
    startDate: new Date(2025, 2, 1),
    endDate: new Date(2025, 2, 30),
    progress: 20,
    dependencies: ["togaf-5"],
    metadata: { type: "Architecture Deliverable", phase: "Phase B" },
    createdAt: new Date("2025-03-01"),
    updatedAt: new Date("2025-03-05"),
  },

  // Phase C: Information Systems
  {
    id: "togaf-7",
    title: "Data Architecture Baseline",
    description: "Document current data landscape",
    status: "phase-c",
    frameworkId: "togaf",
    assignee: { id: "user-4", name: "Data Architect", avatar: "DA" },
    priority: "high",
    tags: ["data", "baseline"],
    startDate: new Date(2025, 2, 25),
    endDate: new Date(2025, 3, 20),
    progress: 30,
    dependencies: ["togaf-6"],
    metadata: { type: "Building Block", phase: "Phase C" },
    createdAt: new Date("2025-03-25"),
    updatedAt: new Date("2025-03-25"),
  },
  {
    id: "togaf-8",
    title: "Application Portfolio Assessment",
    description: "Assess current application landscape",
    status: "phase-c",
    frameworkId: "togaf",
    assignee: { id: "user-5", name: "App Architect", avatar: "AA" },
    priority: "medium",
    tags: ["applications", "assessment"],
    startDate: new Date(2025, 3, 10),
    endDate: new Date(2025, 4, 5),
    progress: 15,
    dependencies: ["togaf-6"],
    metadata: { type: "Work Package", phase: "Phase C" },
    createdAt: new Date("2025-04-10"),
    updatedAt: new Date("2025-04-10"),
  },

  // Phase D: Technology Architecture
  {
    id: "togaf-9",
    title: "Technology Standards Definition",
    description: "Define technology standards and patterns",
    status: "phase-d",
    frameworkId: "togaf",
    assignee: { id: "user-6", name: "Tech Architect", avatar: "TA" },
    priority: "high",
    tags: ["technology", "standards"],
    startDate: new Date(2025, 4, 1),
    endDate: new Date(2025, 4, 25),
    progress: 0,
    dependencies: ["togaf-8"],
    metadata: { type: "Architecture Deliverable", phase: "Phase D" },
    createdAt: new Date("2025-05-01"),
    updatedAt: new Date("2025-05-01"),
  },
  {
    id: "togaf-10",
    title: "Infrastructure Architecture",
    description: "Design target infrastructure architecture",
    status: "phase-d",
    frameworkId: "togaf",
    assignee: { id: "user-6", name: "Tech Architect", avatar: "TA" },
    priority: "medium",
    tags: ["infrastructure", "design"],
    startDate: new Date(2025, 4, 20),
    endDate: new Date(2025, 5, 15),
    progress: 0,
    metadata: { type: "Building Block", phase: "Phase D" },
    createdAt: new Date("2025-05-20"),
    updatedAt: new Date("2025-05-20"),
  },

  // Phase E&F: Opportunities & Migration Planning
  {
    id: "togaf-11",
    title: "Gap Analysis",
    description: "Identify gaps between baseline and target",
    status: "phase-ef",
    frameworkId: "togaf",
    assignee: { id: "user-1", name: "Architecture Lead", avatar: "AL" },
    priority: "critical",
    tags: ["analysis", "gaps"],
    startDate: new Date(2025, 5, 10),
    endDate: new Date(2025, 6, 5),
    progress: 0,
    dependencies: ["togaf-10"],
    metadata: { type: "Work Package", phase: "Phase E&F", isMilestone: true },
    createdAt: new Date("2025-06-10"),
    updatedAt: new Date("2025-06-10"),
  },
  {
    id: "togaf-12",
    title: "Migration Strategy",
    description: "Develop migration and transition strategy",
    status: "phase-ef",
    frameworkId: "togaf",
    assignee: { id: "user-7", name: "Program Manager", avatar: "PM" },
    priority: "high",
    tags: ["migration", "strategy"],
    startDate: new Date(2025, 6, 1),
    endDate: new Date(2025, 6, 30),
    progress: 0,
    dependencies: ["togaf-11"],
    metadata: { type: "Architecture Deliverable", phase: "Phase E&F" },
    createdAt: new Date("2025-07-01"),
    updatedAt: new Date("2025-07-01"),
  },

  // Phase G: Implementation Governance
  {
    id: "togaf-13",
    title: "Architecture Contracts",
    description: "Establish implementation contracts",
    status: "phase-g",
    frameworkId: "togaf",
    assignee: { id: "user-1", name: "Architecture Lead", avatar: "AL" },
    priority: "high",
    tags: ["contracts", "governance"],
    startDate: new Date(2025, 7, 1),
    endDate: new Date(2025, 7, 20),
    progress: 0,
    dependencies: ["togaf-12"],
    metadata: { type: "Deliverable", phase: "Phase G" },
    createdAt: new Date("2025-08-01"),
    updatedAt: new Date("2025-08-01"),
  },
  {
    id: "togaf-14",
    title: "Implementation Oversight",
    description: "Monitor and govern implementation",
    status: "phase-g",
    frameworkId: "togaf",
    assignee: { id: "user-7", name: "Program Manager", avatar: "PM" },
    priority: "medium",
    tags: ["oversight", "monitoring"],
    startDate: new Date(2025, 7, 15),
    endDate: new Date(2025, 9, 30),
    progress: 0,
    metadata: { type: "Work Package", phase: "Phase G" },
    createdAt: new Date("2025-08-15"),
    updatedAt: new Date("2025-08-15"),
  },

  // Phase H: Change Management
  {
    id: "togaf-15",
    title: "Architecture Change Requests",
    description: "Process architecture change requests",
    status: "phase-h",
    frameworkId: "togaf",
    assignee: { id: "user-1", name: "Architecture Lead", avatar: "AL" },
    priority: "medium",
    tags: ["change", "requests"],
    startDate: new Date(2025, 10, 1),
    endDate: new Date(2025, 10, 30),
    progress: 0,
    metadata: { type: "Process", phase: "Phase H" },
    createdAt: new Date("2025-11-01"),
    updatedAt: new Date("2025-11-01"),
  },
  {
    id: "togaf-16",
    title: "Architecture Compliance Review",
    description: "Review architecture compliance",
    status: "phase-h",
    frameworkId: "togaf",
    assignee: { id: "user-8", name: "Quality Lead", avatar: "QL" },
    priority: "high",
    tags: ["compliance", "review"],
    startDate: new Date(2025, 11, 1),
    endDate: new Date(2025, 11, 20),
    progress: 0,
    metadata: { type: "Architecture Deliverable", phase: "Phase H" },
    createdAt: new Date("2025-12-01"),
    updatedAt: new Date("2025-12-01"),
  },
]

// PRINCE2 mock tasks
export const prince2MockTasks: GanttTask[] = [
  {
    id: "prince2-1",
    title: "Appoint Executive and Project Manager",
    description: "Assign key project roles",
    status: "starting-up",
    frameworkId: "prince2",
    assignee: { id: "user-1", name: "PMO Lead", avatar: "PL" },
    priority: "critical",
    tags: ["governance", "roles"],
    startDate: new Date(2025, 0, 1),
    endDate: new Date(2025, 0, 5),
    progress: 100,
    metadata: { type: "Decision Point", phase: "Starting Up" },
    createdAt: new Date("2025-01-01"),
    updatedAt: new Date("2025-01-05"),
  },
  {
    id: "prince2-2",
    title: "Design and Appoint Project Board",
    description: "Set up project governance structure",
    status: "starting-up",
    frameworkId: "prince2",
    assignee: { id: "user-1", name: "PMO Lead", avatar: "PL" },
    priority: "high",
    tags: ["governance", "board"],
    startDate: new Date(2025, 0, 3),
    endDate: new Date(2025, 0, 10),
    progress: 100,
    dependencies: ["prince2-1"],
    metadata: { type: "Work Package", phase: "Starting Up" },
    createdAt: new Date("2025-01-03"),
    updatedAt: new Date("2025-01-10"),
  },
  {
    id: "prince2-3",
    title: "Project Brief",
    description: "Create initial project brief",
    status: "initiating",
    frameworkId: "prince2",
    assignee: { id: "user-2", name: "Project Manager", avatar: "PM" },
    priority: "high",
    tags: ["planning", "documentation"],
    startDate: new Date(2025, 0, 8),
    endDate: new Date(2025, 0, 20),
    progress: 90,
    dependencies: ["prince2-2"],
    metadata: { type: "Deliverable", phase: "Initiating", isMilestone: true },
    createdAt: new Date("2025-01-08"),
    updatedAt: new Date("2025-01-18"),
  },
  {
    id: "prince2-4",
    title: "Detailed Project Plan",
    description: "Develop comprehensive project plan",
    status: "initiating",
    frameworkId: "prince2",
    assignee: { id: "user-2", name: "Project Manager", avatar: "PM" },
    priority: "critical",
    tags: ["planning", "schedule"],
    startDate: new Date(2025, 0, 18),
    endDate: new Date(2025, 1, 10),
    progress: 75,
    dependencies: ["prince2-3"],
    metadata: { type: "Deliverable", phase: "Initiating" },
    createdAt: new Date("2025-01-18"),
    updatedAt: new Date("2025-02-05"),
  },

  // Stage 1: Foundation
  {
    id: "prince2-5",
    title: "Requirements Gathering",
    description: "Collect and document requirements",
    status: "stage-1",
    frameworkId: "prince2",
    assignee: { id: "user-3", name: "Business Analyst", avatar: "BA" },
    priority: "high",
    tags: ["requirements", "analysis"],
    startDate: new Date(2025, 1, 8),
    endDate: new Date(2025, 1, 28),
    progress: 90,
    dependencies: ["prince2-4"],
    metadata: { type: "Work Package", phase: "Stage 1" },
    createdAt: new Date("2025-02-08"),
    updatedAt: new Date("2025-02-25"),
  },
  {
    id: "prince2-6",
    title: "Stage 1 Approval",
    description: "Obtain approval for next stage",
    status: "stage-1",
    frameworkId: "prince2",
    assignee: { id: "user-2", name: "Project Manager", avatar: "PM" },
    priority: "critical",
    tags: ["approval", "gate"],
    startDate: new Date(2025, 1, 25),
    endDate: new Date(2025, 1, 28),
    progress: 100,
    dependencies: ["prince2-5"],
    metadata: { type: "Decision Point", phase: "Stage 1", isMilestone: true },
    createdAt: new Date("2025-02-25"),
    updatedAt: new Date("2025-02-28"),
  },

  // Stage 2: Development
  {
    id: "prince2-7",
    title: "Solution Design",
    description: "Design technical solution",
    status: "stage-2",
    frameworkId: "prince2",
    assignee: { id: "user-4", name: "Tech Lead", avatar: "TL" },
    priority: "high",
    tags: ["design", "architecture"],
    startDate: new Date(2025, 2, 1),
    endDate: new Date(2025, 2, 20),
    progress: 65,
    dependencies: ["prince2-6"],
    metadata: { type: "Deliverable", phase: "Stage 2" },
    createdAt: new Date("2025-03-01"),
    updatedAt: new Date("2025-03-15"),
  },
  {
    id: "prince2-8",
    title: "Development Execution",
    description: "Build and test solution components",
    status: "stage-2",
    frameworkId: "prince2",
    assignee: { id: "user-5", name: "Dev Team", avatar: "DT" },
    priority: "high",
    tags: ["development", "testing"],
    startDate: new Date(2025, 2, 15),
    endDate: new Date(2025, 3, 30),
    progress: 45,
    dependencies: ["prince2-7"],
    metadata: { type: "Work Package", phase: "Stage 2" },
    createdAt: new Date("2025-03-15"),
    updatedAt: new Date("2025-04-10"),
  },

  // Stage 3: Delivery
  {
    id: "prince2-9",
    title: "UAT Preparation",
    description: "Prepare for user acceptance testing",
    status: "stage-3",
    frameworkId: "prince2",
    assignee: { id: "user-3", name: "Business Analyst", avatar: "BA" },
    priority: "high",
    tags: ["uat", "testing"],
    startDate: new Date(2025, 4, 1),
    endDate: new Date(2025, 4, 15),
    progress: 20,
    dependencies: ["prince2-8"],
    metadata: { type: "Work Package", phase: "Stage 3" },
    createdAt: new Date("2025-05-01"),
    updatedAt: new Date("2025-05-05"),
  },
  {
    id: "prince2-10",
    title: "Production Deployment",
    description: "Deploy solution to production",
    status: "stage-3",
    frameworkId: "prince2",
    assignee: { id: "user-4", name: "Tech Lead", avatar: "TL" },
    priority: "critical",
    tags: ["deployment", "production"],
    startDate: new Date(2025, 4, 20),
    endDate: new Date(2025, 5, 5),
    progress: 0,
    dependencies: ["prince2-9"],
    metadata: { type: "Deliverable", phase: "Stage 3", isMilestone: true },
    createdAt: new Date("2025-05-20"),
    updatedAt: new Date("2025-05-20"),
  },

  // Closing
  {
    id: "prince2-11",
    title: "Project Review",
    description: "Conduct post-implementation review",
    status: "closing",
    frameworkId: "prince2",
    assignee: { id: "user-2", name: "Project Manager", avatar: "PM" },
    priority: "medium",
    tags: ["review", "lessons"],
    startDate: new Date(2025, 5, 1),
    endDate: new Date(2025, 5, 15),
    progress: 0,
    dependencies: ["prince2-10"],
    metadata: { type: "Work Package", phase: "Closing" },
    createdAt: new Date("2025-06-01"),
    updatedAt: new Date("2025-06-01"),
  },
  {
    id: "prince2-12",
    title: "Project Closure",
    description: "Formally close the project",
    status: "closing",
    frameworkId: "prince2",
    assignee: { id: "user-2", name: "Project Manager", avatar: "PM" },
    priority: "high",
    tags: ["closure", "handover"],
    startDate: new Date(2025, 5, 10),
    endDate: new Date(2025, 5, 25),
    progress: 0,
    dependencies: ["prince2-11"],
    metadata: { type: "Decision Point", phase: "Closing", isMilestone: true },
    createdAt: new Date("2025-06-10"),
    updatedAt: new Date("2025-06-10"),
  },
]

// PMBOK mock tasks
export const pmbokMockTasks: GanttTask[] = [
  {
    id: "pmbok-1",
    title: "Develop Project Charter",
    description: "Create and authorize project charter",
    status: "integration",
    frameworkId: "pmbok",
    assignee: { id: "user-1", name: "Project Manager", avatar: "PM" },
    priority: "critical",
    tags: ["charter", "initiation"],
    startDate: new Date(2025, 0, 1),
    endDate: new Date(2025, 0, 15),
    progress: 100,
    metadata: { type: "Deliverable", phase: "Initiating", isMilestone: true },
    createdAt: new Date("2025-01-01"),
    updatedAt: new Date("2025-01-15"),
  },
  {
    id: "pmbok-2",
    title: "Define Scope",
    description: "Create detailed project scope statement",
    status: "scope",
    frameworkId: "pmbok",
    assignee: { id: "user-2", name: "Business Analyst", avatar: "BA" },
    priority: "high",
    tags: ["scope", "requirements"],
    startDate: new Date(2025, 0, 10),
    endDate: new Date(2025, 0, 28),
    progress: 85,
    dependencies: ["pmbok-1"],
    metadata: { type: "Deliverable", phase: "Planning" },
    createdAt: new Date("2025-01-10"),
    updatedAt: new Date("2025-01-25"),
  },
  {
    id: "pmbok-3",
    title: "Create WBS",
    description: "Develop work breakdown structure",
    status: "scope",
    frameworkId: "pmbok",
    assignee: { id: "user-2", name: "Business Analyst", avatar: "BA" },
    priority: "high",
    tags: ["wbs", "decomposition"],
    startDate: new Date(2025, 0, 25),
    endDate: new Date(2025, 1, 10),
    progress: 60,
    dependencies: ["pmbok-2"],
    metadata: { type: "Deliverable", phase: "Planning" },
    createdAt: new Date("2025-01-25"),
    updatedAt: new Date("2025-02-05"),
  },
  {
    id: "pmbok-4",
    title: "Develop Project Schedule",
    description: "Create detailed project schedule",
    status: "schedule",
    frameworkId: "pmbok",
    assignee: { id: "user-1", name: "Project Manager", avatar: "PM" },
    priority: "high",
    tags: ["schedule", "timeline"],
    startDate: new Date(2025, 1, 5),
    endDate: new Date(2025, 1, 25),
    progress: 40,
    dependencies: ["pmbok-3"],
    metadata: { type: "Activity", phase: "Planning" },
    createdAt: new Date("2025-02-05"),
    updatedAt: new Date("2025-02-15"),
  },
  {
    id: "pmbok-5",
    title: "Estimate Costs",
    description: "Develop cost estimates for project",
    status: "cost",
    frameworkId: "pmbok",
    assignee: { id: "user-3", name: "Cost Analyst", avatar: "CA" },
    priority: "high",
    tags: ["budget", "estimation"],
    startDate: new Date(2025, 1, 15),
    endDate: new Date(2025, 2, 5),
    progress: 30,
    dependencies: ["pmbok-3"],
    metadata: { type: "Activity", phase: "Planning" },
    createdAt: new Date("2025-02-15"),
    updatedAt: new Date("2025-02-20"),
  },

  // Quality Management
  {
    id: "pmbok-6",
    title: "Plan Quality Management",
    description: "Define quality standards and processes",
    status: "quality",
    frameworkId: "pmbok",
    assignee: { id: "user-4", name: "Quality Manager", avatar: "QM" },
    priority: "medium",
    tags: ["quality", "standards"],
    startDate: new Date(2025, 2, 1),
    endDate: new Date(2025, 2, 20),
    progress: 50,
    dependencies: ["pmbok-2"],
    metadata: { type: "Activity", phase: "Planning" },
    createdAt: new Date("2025-03-01"),
    updatedAt: new Date("2025-03-10"),
  },
  {
    id: "pmbok-7",
    title: "Quality Assurance Reviews",
    description: "Conduct QA reviews and audits",
    status: "quality",
    frameworkId: "pmbok",
    assignee: { id: "user-4", name: "Quality Manager", avatar: "QM" },
    priority: "high",
    tags: ["qa", "audit"],
    startDate: new Date(2025, 3, 1),
    endDate: new Date(2025, 5, 30),
    progress: 15,
    dependencies: ["pmbok-6"],
    metadata: { type: "Activity", phase: "Executing" },
    createdAt: new Date("2025-04-01"),
    updatedAt: new Date("2025-04-10"),
  },

  // Resource Management
  {
    id: "pmbok-8",
    title: "Acquire Project Team",
    description: "Staff project with required resources",
    status: "resources",
    frameworkId: "pmbok",
    assignee: { id: "user-5", name: "Resource Manager", avatar: "RM" },
    priority: "critical",
    tags: ["staffing", "team"],
    startDate: new Date(2025, 1, 10),
    endDate: new Date(2025, 1, 28),
    progress: 80,
    dependencies: ["pmbok-1"],
    metadata: { type: "Activity", phase: "Executing" },
    createdAt: new Date("2025-02-10"),
    updatedAt: new Date("2025-02-25"),
  },
  {
    id: "pmbok-9",
    title: "Develop Team",
    description: "Team building and training activities",
    status: "resources",
    frameworkId: "pmbok",
    assignee: { id: "user-5", name: "Resource Manager", avatar: "RM" },
    priority: "medium",
    tags: ["training", "development"],
    startDate: new Date(2025, 2, 1),
    endDate: new Date(2025, 3, 15),
    progress: 40,
    dependencies: ["pmbok-8"],
    metadata: { type: "Activity", phase: "Executing" },
    createdAt: new Date("2025-03-01"),
    updatedAt: new Date("2025-03-20"),
  },

  // Communications Management
  {
    id: "pmbok-10",
    title: "Communications Plan",
    description: "Define communication strategy and channels",
    status: "communications",
    frameworkId: "pmbok",
    assignee: { id: "user-1", name: "Project Manager", avatar: "PM" },
    priority: "high",
    tags: ["communications", "stakeholders"],
    startDate: new Date(2025, 1, 5),
    endDate: new Date(2025, 1, 15),
    progress: 100,
    dependencies: ["pmbok-1"],
    metadata: { type: "Deliverable", phase: "Planning" },
    createdAt: new Date("2025-02-05"),
    updatedAt: new Date("2025-02-15"),
  },

  // Risk Management
  {
    id: "pmbok-11",
    title: "Identify Risks",
    description: "Identify and document project risks",
    status: "risk",
    frameworkId: "pmbok",
    assignee: { id: "user-6", name: "Risk Manager", avatar: "RM" },
    priority: "high",
    tags: ["risk", "analysis"],
    startDate: new Date(2025, 2, 5),
    endDate: new Date(2025, 2, 25),
    progress: 60,
    dependencies: ["pmbok-2"],
    metadata: { type: "Activity", phase: "Planning" },
    createdAt: new Date("2025-03-05"),
    updatedAt: new Date("2025-03-20"),
  },
  {
    id: "pmbok-12",
    title: "Risk Response Planning",
    description: "Develop risk mitigation strategies",
    status: "risk",
    frameworkId: "pmbok",
    assignee: { id: "user-6", name: "Risk Manager", avatar: "RM" },
    priority: "critical",
    tags: ["mitigation", "planning"],
    startDate: new Date(2025, 2, 20),
    endDate: new Date(2025, 3, 15),
    progress: 35,
    dependencies: ["pmbok-11"],
    metadata: { type: "Deliverable", phase: "Planning" },
    createdAt: new Date("2025-03-20"),
    updatedAt: new Date("2025-04-05"),
  },

  // Procurement Management
  {
    id: "pmbok-13",
    title: "Plan Procurements",
    description: "Identify what to procure externally",
    status: "procurement",
    frameworkId: "pmbok",
    assignee: { id: "user-7", name: "Procurement Lead", avatar: "PL" },
    priority: "medium",
    tags: ["procurement", "vendors"],
    startDate: new Date(2025, 3, 1),
    endDate: new Date(2025, 3, 20),
    progress: 25,
    dependencies: ["pmbok-5"],
    metadata: { type: "Activity", phase: "Planning" },
    createdAt: new Date("2025-04-01"),
    updatedAt: new Date("2025-04-10"),
  },

  // Stakeholder Management
  {
    id: "pmbok-14",
    title: "Identify Stakeholders",
    description: "Document stakeholder requirements and expectations",
    status: "stakeholder",
    frameworkId: "pmbok",
    assignee: { id: "user-2", name: "Business Analyst", avatar: "BA" },
    priority: "high",
    tags: ["stakeholders", "engagement"],
    startDate: new Date(2025, 0, 5),
    endDate: new Date(2025, 0, 20),
    progress: 100,
    dependencies: ["pmbok-1"],
    metadata: { type: "Activity", phase: "Initiating" },
    createdAt: new Date("2025-01-05"),
    updatedAt: new Date("2025-01-20"),
  },
  {
    id: "pmbok-15",
    title: "Manage Stakeholder Engagement",
    description: "Ongoing stakeholder communications and management",
    status: "stakeholder",
    frameworkId: "pmbok",
    assignee: { id: "user-1", name: "Project Manager", avatar: "PM" },
    priority: "medium",
    tags: ["engagement", "communications"],
    startDate: new Date(2025, 2, 1),
    endDate: new Date(2025, 6, 31),
    progress: 40,
    dependencies: ["pmbok-14"],
    metadata: { type: "Activity", phase: "Executing" },
    createdAt: new Date("2025-03-01"),
    updatedAt: new Date("2025-05-15"),
  },
]

// Main data export function
export function getMockGanttTasks(frameworkId: string): GanttTask[] {
  switch (frameworkId) {
    case "togaf":
      return togafMockTasks
    case "prince2":
      return prince2MockTasks
    case "pmbok":
      return pmbokMockTasks
    default:
      return []
  }
}
